# Generated by Django 2.2.12 on 2023-02-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_obat', models.CharField(max_length=10)),
                ('nama_obat', models.CharField(max_length=25)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Transaksi',
        ),
    ]
