# Generated by Django 2.2.12 on 2023-02-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20230201_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pelanggan', models.CharField(max_length=10)),
                ('nama_pelanggan', models.CharField(max_length=25)),
                ('alamat_pelanggan', models.CharField(max_length=25)),
                ('pekerjaan', models.CharField(max_length=25)),
            ],
        ),
    ]
