# Generated by Django 2.2.12 on 2023-02-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_stok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_karyawan', models.CharField(max_length=10)),
                ('nama_karyawan', models.CharField(max_length=25)),
                ('jenis_kelamin', models.CharField(max_length=25)),
                ('no_tlp', models.IntegerField()),
            ],
        ),
    ]
