# Generated by Django 2.2.12 on 2023-02-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_karyawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtransaksi', models.CharField(max_length=10)),
                ('kodebrg', models.CharField(max_length=8)),
                ('subtotal', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Detailtrans',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
